[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/livestream"
  to = "https://youtu.be/jL5LGzdOoBk"
  status = 301

[[redirects]]
  from = "/welcome"
  to = "https://help.osoc.be/global/"
  status = 301

[[redirects]]
  from = "/2019"
  to = "/editions/2019"
  status = 301

[[redirects]]
  from = "/2020"
  to = "/editions/2020"
  status = 301

[[redirects]]
  from = "/companies"
  to = "/partners"
  status = 301
